name: Check redoc

on:
  schedule:
    - cron: "20 0 * * *"

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false

      - name: Set up Node
        uses: actions/setup-node@v6

      - name: Update flask-openapi-redoc
        id: update_redoc
        run: |
          cd ./flask-openapi-redoc/flask_openapi_redoc
          old_version=$(cat __version__.py | grep -oP '(?<=__version__ = ").*(?=")')
          new_version=$(npm show redoc version)
          if [ "${new_version}" != "${old_version}" ]; then
            curl -L https://cdn.jsdelivr.net/npm/redoc@${new_version}/bundles/redoc.standalone.js \
                 -o ./templates/redoc/js/redoc.standalone.js
            echo -e "# -*- coding: utf-8 -*-\n\n__version__ = \"${new_version}\"" > __version__.py
            echo "new_version=${new_version}" >> $GITHUB_OUTPUT
            echo "is_update=true" >> $GITHUB_OUTPUT
          else
            echo "is_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Git Commit
        if: ${{ steps.update_redoc.outputs.is_update == 'true' }}
        id: git_commit
        run: |
          new_version=${{ steps.update_redoc.outputs.new_version }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update redoc ${new_version}"
          git push origin main

      - name: Release flask-openapi-redoc
        if: ${{ steps.git_commit.outcome == 'success' }}
        run: |
          cd flask-openapi-redoc
          uv build
          uv publish
