name: Check swagger

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false

      - name: Set up Node
        uses: actions/setup-node@v6

      - name: Update flask-openapi-swagger
        id: update_swagger
        run: |
          cd ./flask-openapi-swagger/flask_openapi_swagger
          old_version=$(cat __version__.py | grep -oP '(?<=__version__ = ").*(?=")')
          new_version=$(npm show swagger-ui-dist version)
          if [ "${new_version}" != "${old_version}" ]; then
            curl -L https://cdn.jsdelivr.net/npm/swagger-ui-dist@${new_version}/swagger-ui.css \
                 -o ./templates/swagger/css/swagger-ui.css
            curl -L https://cdn.jsdelivr.net/npm/swagger-ui-dist@${new_version}/swagger-ui-bundle.js \
                 -o ./templates/swagger/js/swagger-ui-bundle.js
            curl -L https://cdn.jsdelivr.net/npm/swagger-ui-dist@${new_version}/swagger-ui-standalone-preset.js \
                 -o ./templates/swagger/js/swagger-ui-standalone-preset.js
            echo -e "# -*- coding: utf-8 -*-\n\n__version__ = \"${new_version}\"" > __version__.py
            echo "new_version=${new_version}" >> $GITHUB_OUTPUT
            echo "is_update=true" >> $GITHUB_OUTPUT
          else
            echo "is_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Git Commit
        if: ${{ steps.update_swagger.outputs.is_update == 'true' }}
        id: git_commit
        run: |
          new_version=${{ steps.update_swagger.outputs.new_version }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update swagger ${new_version}"
          git push origin main

      - name: Release flask-openapi-swagger
        if: ${{ steps.git_commit.outcome == 'success' }}
        run: |
          cd flask-openapi-swagger
          uv build
          uv publish
